name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'micro-frontends/simple-mf-reactjs-aws/container/**'

defaults:
  run:
    working-directory: micro-frontends/simple-mf-reactjs-aws/container

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}
        aws-region: us-east-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://{{secrets.AWS_S3_BUCKET_NAME}}
